# Pandas

In [1]:
import pandas as pd

In [5]:
student=pd.read_csv(r'C:\Users\krish\Downloads\archive\Student_performance_data _.csv')

In [6]:
student

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [7]:
student.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [8]:
student.tail()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [9]:
student.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB

In [12]:
student.columns

Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA',
       'GradeClass'],
      dtype='object')

In [13]:
student.shape

(2392, 15)

In [14]:
student.shape[1]

15

In [15]:
student.shape[0]

2392

In [16]:
student[["Age"]]

      Age
0      17
1      18
2      15
3      17
4      17
...   ...
2387   18
2388   17
2389   16
2390   16
2391   16

[2392 rows x 1 columns]

In [17]:
student[["Sports"]]

      Sports
0          0
1          0
2          0
3          0
4          0
...      ...
2387       0
2388       1
2389       0
2390       1
2391       0

[2392 rows x 1 columns]

In [18]:
student[["Age","Sports"]]

      Age  Sports
0      17       0
1      18       0
2      15       0
3      17       0
4      17       0
...   ...     ...
2387   18       0
2388   17       1
2389   16       0
2390   16       1
2391   16       0

[2392 rows x 2 columns]

In [21]:
student.loc[student['Age']==23]

Empty DataFrame
Columns: [StudentID, Age, Gender, Ethnicity, ParentalEducation, StudyTimeWeekly, Absences, Tutoring, ParentalSupport, Extracurricular, Sports, Music, Volunteering, GPA, GradeClass]
Index: []

In [22]:
student.Age.unique

<bound method Series.unique of 0       17
1       18
2       15
3       17
4       17
        ..
2387    18
2388    17
2389    16
2390    16
2391    16
Name: Age, Length: 2392, dtype: int64>

In [24]:
student.Age.value_counts()

Age
15    630
16    593
17    587
18    582
Name: count, dtype: int64

In [25]:
student.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [26]:
student.iloc[15:30,2:7]

    Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  Absences
15       0          0                  2         9.728101        17
16       0          3                  1        10.098656        14
17       1          0                  0         3.528238        16
18       0          1                  3        16.254658        29
19       0          0                  1        10.835206         9
20       1          0                  3         2.621597         2
21       0          0                  2        15.323142        25
22       1          1                  0        18.648880        29
23       1          3                  4        18.946138        20
24       1          0                  1         7.380355        15
25       1          0                  3         2.710337         5
26       0          0                  1        10.367993         2
27       1          0                  3         2.252185         8
28       0          0                  0        18.679748        10
29       0          0                  2         3.671593        20